### ISSUE TITLE
unable to import make_logger

### ISSUE THREAD

**Issue by momeara** [flatkinson/standardiser#5]
With the recent changes, 
```
import make_logger
logger = make_logger.run(__name__)
```

I am now getting
```
ImportError: No module named make_logger
```

What is this module? If I revert it back to 
```
import logging
logger = logging.getLogger(__name__)
```
I no longer get the error.

**Comment by mmysinger** [comment]
Just hit this same issue, and I also note that make_logger is not anywhere to be found in the repo. To fix I created make_logger below, but I still had to:

`sed 's/import make_logger/from standardiser import make_logger/' -i *.py`

standardiser/make_logger.py:
```
def run(name):
        return logging.getLogger(name)
```

**Comment by momeara** [comment]
What does that add over just calling `logging.getLogger` directly?

**Comment by mmysinger** [comment]
Nothing really. I fixed it first and found this thread second :P

**Comment by flatkinson** [comment]
OK, this should be fixed; make_logger is just a small module to hide some of the boilerplate around creating a logger.
